# Nome do workflow, aparece na aba "Actions"
name: Pipeline CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "src/**"                # Só dispara se os arquivos do código fonte mudarem
      - ".github/workflows/**"  # Ou se o próprio pipeline mudar
  workflow_dispatch:            # Habilita o botão "Run workflow" no GitHub Actions

jobs:
  # ===============================
  # Job 1: Build
  # ===============================
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Instalação das dependências
        run: npm install

      - name: Rodar o build
        run: npm run build
        env:
          AUTORIZATION: ${{ secrets.AUTORIZATION }}

  # ===============================
  # Job 2: Testes
  # ===============================
  test:
    runs-on: ubuntu-latest
    needs: build   # Só roda depois do build

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Rodar o Lint
        run: npm run lint
        
      - name: Verificar formatação
        run: npm run format -- --check

      - name: Rodar testes
        run: npm run test
