# Nome do workflow, aparece na aba "Actions"
name: Pipeline CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch: # Habilita o botão "Run workflow" no GitHub Actions

jobs:
  # Primeiro job: build
  build:
    runs-on: ubuntu-latest # Imagem da máquina no CI

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalação das dependências
        run: npm install

      - name: Rodar o build
        run: npm run build
